### ISSUE TITLE
I can't seem to get it working with coc

### ISSUE THREAD

**Issue by darzok0914** [yaegassy/coc-pysen#7] opened 2021-11-12 17:18 UTC
hi, 

would it be possible to have a step by step small tuto to get it working with Coc. I wasn't able to get anything working. I followed the install process but nothing is happening. 

Do I need to update my CocConfil.json ? or install other dependencies ?

**Comment by yaegassy** [comment] 2021-11-14 02:16
The pysen-ls (Language Server) used by coc-pysen is currently not maintained. :(

Probably the reason why it doesn't work is that pysen-ls is not able to support the black version upgrade.

I set the default value of the black version installed with `:CocComannd pysen.installServer` to "v20.8b1" because I have confirmed that black works with "v20.8b1" in my environment.

I've updated coc-pysen, try it out! https://github.com/yaegassy/coc-pysen/commit/8a26ddff819321023bb853d07fb3315fedcdfc81

1. `:CocUpdate`
2. `:CocComannd pysen.installServer`

Also, as an additional note, `pyproject.toml` needs to be configured to run "pysen-ls". https://github.com/yaegassy/coc-pysen#require-pyprojecttoml

**Comment by yaegassy** [comment] 2021-11-14 02:19
Ref: https://github.com/yaegassy/coc-pysen/issues/3

**Comment by yaegassy** [comment] 2021-11-14 02:20
The latest version of `pysen-ls` will be released soon and may fix this problem. https://github.com/bonprosoft/pysen-ls/pull/7

**Comment by yaegassy** [comment] 2021-11-15 02:14
"v0.1.2" of `pysen-ls`, which is used by coc-pysen, has been released. The `black` issue described in this issue has been resolved.  https://pypi.org/project/pysen-ls/0.1.2/

I've already changed `coc-pysen` to install the latest version of "pysen-ls", even with a built-in installation. Try it out.

If you have any other issues, please contact me via another issue.

Step by step tutorial, but I'm sorry. I'm not very good at English. PR is welcome!

**Closed as completed by yaegassy** 2021-11-15 02:14 UTC
